"""
Generates a structured, court-admissible expert opinion report
from an AnalysisResult, as plain text (formatted for display/PDF).
"""

from __future__ import annotations
from datetime import datetime
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from analyzer import AnalysisResult


_DIVIDER = "=" * 72
_SECTION = "-" * 72


def generate_report(result: "AnalysisResult", examiner_name: str = "Forensic Document Examiner") -> str:
    now = datetime.now()
    date_str = now.strftime("%d %B %Y")
    time_str = now.strftime("%H:%M hrs")
    report_id = now.strftime("FDE-%Y%m%d-%H%M%S")

    lines = []

    # ── Header ──────────────────────────────────────────────────────────────
    lines += [
        _DIVIDER,
        "              FORENSIC DOCUMENT EXAMINATION REPORT",
        "           AI-Assisted Analysis — For Official Use Only",
        _DIVIDER,
        "",
        f"  Report Reference   : {report_id}",
        f"  Date of Examination: {date_str}",
        f"  Time               : {time_str}",
        f"  Prepared By        : {examiner_name}",
        f"  Document Type      : {result.document_type}",
        "",
        _DIVIDER,
        "  SECTION 1 — EXECUTIVE SUMMARY",
        _DIVIDER,
        "",
        f"  Overall Forgery Confidence : {result.overall_confidence_label}",
        f"                               ({int(result.overall_confidence * 100)}%)",
        f"  Examination Verdict        : {result.verdict}",
        f"  Total Anomaly Categories   : {len(result.findings)}",
        f"  Significant Anomalies      : {result.anomaly_count}",
        f"  Primary Anomaly Type       : {result.primary_anomaly}",
        "",
    ]

    # ── Opinion Statement ────────────────────────────────────────────────────
    lines += [
        _DIVIDER,
        "  SECTION 2 — EXPERT OPINION",
        _DIVIDER,
        "",
    ]
    lines += _opinion_text(result)
    lines.append("")

    # ── Findings ────────────────────────────────────────────────────────────
    lines += [
        _DIVIDER,
        "  SECTION 3 — DETAILED FINDINGS",
        _DIVIDER,
        "",
    ]

    for i, finding in enumerate(result.findings, 1):
        bar = _confidence_bar(finding.confidence)
        lines += [
            f"  [{i}] {finding.label}",
            f"      Confidence  : {finding.confidence_label} ({int(finding.confidence * 100)}%)  {bar}",
            f"      Standard    : {finding.standard}",
            f"      Scope       : {finding.standard_description}",
            "",
            "      Observation recorded:",
            *[f"        {ln}" for ln in _wrap(finding.raw_observation, 60)],
            "",
        ]
        if finding.matched_keywords:
            lines.append(f"      Forensic markers identified: {', '.join(finding.matched_keywords[:6])}")
        lines += [
            "",
            "      Applicable examination indicators:",
        ]
        for ind in finding.relevant_indicators:
            lines.append(f"        • {ind}")
        lines += ["", _SECTION, ""]

    # ── Standards Referenced ─────────────────────────────────────────────────
    lines += [
        _DIVIDER,
        "  SECTION 4 — EXAMINATION STANDARDS APPLIED",
        _DIVIDER,
        "",
    ]
    seen_standards = set()
    for f in result.findings:
        if f.standard not in seen_standards:
            lines.append(f"  • {f.standard}")
            lines.append(f"    {f.standard_description}")
            lines.append("")
            seen_standards.add(f.standard)

    # ── Examiner Notes ───────────────────────────────────────────────────────
    if result.examiner_notes:
        lines += [
            _DIVIDER,
            "  SECTION 5 — EXAMINER NOTES",
            _DIVIDER,
            "",
            *[f"  {ln}" for ln in _wrap(result.examiner_notes, 68)],
            "",
        ]

    # ── Disclaimer ───────────────────────────────────────────────────────────
    lines += [
        _DIVIDER,
        "  DISCLAIMER",
        _DIVIDER,
        "",
        "  This report is generated by an AI-assisted forensic analysis system.",
        "  Findings are based on structured observations entered by the examiner.",
        "  This report is intended to assist — not replace — a qualified Forensic",
        "  Document Examiner (FDE). All conclusions must be independently verified",
        "  by a certified expert before use in legal proceedings.",
        "",
        "  The analysis applies rule-based scoring aligned with internationally",
        "  recognised examination standards (ASTM, SWGMAT, ISO, NIST).",
        "",
        _DIVIDER,
        f"  END OF REPORT  |  {report_id}",
        _DIVIDER,
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _confidence_bar(score: float) -> str:
    filled = round(score * 10)
    return "[" + "█" * filled + "░" * (10 - filled) + "]"


def _wrap(text: str, width: int) -> list:
    """Naive word-wrap."""
    words = text.split()
    lines = []
    current = []
    length = 0
    for word in words:
        if length + len(word) + 1 > width:
            lines.append(" ".join(current))
            current = [word]
            length = len(word)
        else:
            current.append(word)
            length += len(word) + 1
    if current:
        lines.append(" ".join(current))
    return lines


def _opinion_text(result: "AnalysisResult") -> list:
    conf_pct = int(result.overall_confidence * 100)
    verdict = result.verdict
    doc = result.document_type

    if conf_pct >= 70:
        opinion = (
            f"  Based on the structured forensic observations submitted for the "
            f"'{doc}', this examination has identified {result.anomaly_count} "
            f"significant anomal{'ies' if result.anomaly_count != 1 else 'y'} across "
            f"the examined categories. The cumulative forensic indicators establish "
            f"a {result.overall_confidence_label} degree of confidence ({conf_pct}%) "
            f"that the document exhibits characteristics consistent with forgery or "
            f"fraudulent alteration."
        )
        conclusion = (
            f"  It is the opinion of this examination that the submitted document "
            f"is a '{verdict}'. This opinion is supported by corroborating findings "
            f"across multiple forensic examination categories and relevant "
            f"examination standards."
        )
    elif conf_pct >= 40:
        opinion = (
            f"  Forensic examination of the '{doc}' has revealed {result.anomaly_count} "
            f"anomal{'ies' if result.anomaly_count != 1 else 'y'} warranting further "
            f"investigation. A {result.overall_confidence_label} confidence level "
            f"({conf_pct}%) has been assigned, indicating the document displays "
            f"features inconsistent with an authentic specimen."
        )
        conclusion = (
            f"  The examination yields a finding of '{verdict}'. "
            f"Additional physical or digital examination is recommended before "
            f"a definitive conclusion is submitted to legal proceedings."
        )
    else:
        opinion = (
            f"  Examination of the '{doc}' at the current level of submitted "
            f"observations has not produced sufficient forensic indicators to "
            f"conclude that the document is forged. The overall confidence level "
            f"is {result.overall_confidence_label} ({conf_pct}%)."
        )
        conclusion = (
            f"  Preliminary finding: '{verdict}'. "
            f"If further anomalies are observed, the examination should be "
            f"re-submitted with additional detail."
        )

    return [
        *_wrap(opinion, 68),
        "",
        *_wrap(conclusion, 68),
    ]
